### ISSUE TITLE
Cap.09 - Expressões Regulares

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/eloquente-javascript#15]
Tradução do arquivo [09-expressoes-regulares.md](https://github.com/eoop/eloquente-javascript/blob/master/chapters/09-expressoes-regulares.md)

**Original**: [link](http://eloquentjavascript.net/2nd_edition/preview/09_regexp.html)

- [x] Expressões Regulares
- [x] Notação
- [x] Testando por correspondências
- [x] Encontrando um conjunto de caracteres
- [x] Partes repetidas em um pattern
- [x] Agrupando sub-expressões
- [x] Resultados e grupos
- [x] O tipo _data_
- [x] Limites de palavra e _string_
- [x] Alternativas
- [x] O mecanismo de procura #29 
- [x] Backtracking #31 
- [x] The replace method #30 
- [x] Greed #32 
- [x] Dynamically creating RegExp objects #33 
- [x] The search method #34
- [x] The lastIndex property #35 
- [x] Parsing an ini file #37 
- [x] International characters #38
- [x] Summary #38
- [x] Exercises #39 
- [x] Regex golf #40 
- [x] Quoting style #41 
- [x] Numbers again #42

**Comment by vitornogueira** [comment]
@ericdouglas me disponho a revisar o capítulo :wink:

**Comment by randsonjs** [comment]
Isso ae, adicionei essa tarefa para você! :wink:

**Comment by ericdouglas** [comment]
Ótimo! Obrigado @vitornogueira !

**Comment by vitornogueira** [comment]
:+1:

**Comment by letanure** [comment]
:+1:

**Comment by SauloSilva** [comment]
@vitornogueira como estamos na revisão deste capítulo?

**Comment by vitornogueira** [comment]
@SauloSilva fiquei um bom tempo sem trabalhar na revisão, mas retomei o trabalho nesse final de semana. Até sexta eu finalizo :+1:

**Comment by SauloSilva** [comment]
@vitornogueira :+1:

**Comment by ericdouglas** [comment]
Vou adicionar este capítulo a gh-pages.
